version: "3"

services:
  server:
    build: .
    volumes:
      - .:/app
    ports:
      - 9090:9090
    command: "./serverd"
  server-dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/app
    ports:
      - 9090:9090
  test:
    build: .
    volumes:
      - .:/app
    command: bash -c "go test ./... -race -coverprofile=coverage.txt -covermode=atomic -v"
